"""Queens historical backfill parsing and saving. (Minigames cog impl mixin; see minigames.py)."""

import asyncio
import datetime as dt
import io
import json
import logging
import os
import pathlib
import sqlite3
import sys
import time
import zipfile
from types import SimpleNamespace
from zoneinfo import ZoneInfo

import discord
from discord import app_commands
from discord.ext import commands

from tle import constants
from tle.util import codeforces_common as cf_common
from tle.util import discord_common
from tle.util import paginator
from tle.util import tasks
from tle.util.akari_rating import rank_for_rating
from tle.util.minigame_rating import compute_ratings
from tle.util.db.minigame_db import (
    merged_minigame_winners, diff_merged_winners,
)

from tle.cogs._migrate_retry import discord_retry, RetryExhaustedError
from tle.cogs._minigame_common import (
    compute_vs, compute_vs_matchups, compute_streak, compute_longest_streak,
    compute_top, pick_best_results, format_duration, normalize_puzzle_date,
    parse_date_args, resolve_scoring, strip_codeblock, _NO_TIME_BOUND,
)
from tle.cogs._minigame_akari import (
    AKARI_GAME, akari_date_number_mismatch, expected_puzzle_number,
    looks_like_non_pro_akari, puzzle_date_for,
)
from tle.cogs._minigame_guessgame import GUESSGAME_GAME
from tle.cogs._minigame_queens import (
    QUEENS_GAME, normalize_queens_name, parse_queens_leaderboard,
    parse_queens_time, queens_status_flags,
)
from tle.cogs._minigame_stats import (
    plot_akari_performance, plot_akari_rating,
    plot_akari_stats, plot_guessgame_stats, plot_queens_stats,
)
from tle.cogs._minigame_helpers import (
    MinigameCogError, CaseInsensitiveMember, _mg, _safe_member_name,
    _safe_user_name, _safe_cf_handle,
    _legend_name_for, _format_score, _format_akari_history_line,
    _format_minigame_history_line, _format_akari_ban_line, _ScheduledCtx,
)
from tle.cogs._minigame_tables import (
    _PuzzlePlayerInfo, _maybe_parse_puzzle_selector,
    _get_akari_puzzle_table_image_file, _get_akari_rating_table_image_file,
    _get_queens_results_table_image_file,
)
from tle.cogs._minigame_queens_filters import (
    _split_queens_weekday_filter, _filter_queens_weekday_rows,
    _split_queens_rating_date_filter, _split_queens_recalculate_filter,
    _filter_queens_rating_date_rows, _filter_queens_rating_date_history,
    _format_queens_weekday_filter, _queens_weekday_filter_suffix,
    _format_queens_date_filter, _queens_filter_suffix,
    _filter_queens_contested_rating_history,
)
from tle.cogs._minigame_queens_cog import (
    _QueensResolvedEntry, _QueensImportPreview, _QueensImportSaveResult,
    _QueensBackfillResult, _QueensPendingRegistration,
    _QUEENS_CONNECTION_ACCOUNT_KEY, _QUEENS_DEFAULT_CONNECTION_ACCOUNT,
    _QUEENS_ANONYMOUS_LINK_MARKER, _QUEENS_ANONYMOUS_LABEL,
    _QUEENS_ANONYMOUS_FLAGS, _QUEENS_PENDING_REGISTRATION_DELAY,
    _QUEENS_CONNECT_TIMEOUT, _QUEENS_IMPORTER_KEY, _QUEENS_LINKEDIN_NAME_KEY,
    _QUEENS_ADMINS_KEY, _QUEENS_STATE_PATH_KEY, _QUEENS_UPDATE_THROTTLE_PREFIX,
    _QUEENS_UPDATE_THROTTLE_SECONDS, _QUEENS_DAILY_UPDATE_LAST_PREFIX,
    _QUEENS_DAILY_UPDATE_CHECK_INTERVAL, _QUEENS_DAILY_UPDATE_PRECISE_WINDOW,
    _QUEENS_DAILY_UPDATE_TIME, _QUEENS_DAILY_UPDATE_TZ,
    _QUEENS_AUTO_PLAY_MIN_SECONDS, _QUEENS_SCRAPER_TIMEOUT,
    _QUEENS_WHOAMI_TIMEOUT, _QUEENS_PLAYWRIGHT_PLATFORM,
    _QUEENS_STATE_MAX_BYTES, _QUEENS_BACKFILL_MAX_BYTES, _QUEENS_HISTORY_PER_PAGE,
    _parse_queens_date, _queens_puzzle_number_for_date,
    _queens_date_for_puzzle_number, _parse_queens_date_or_number,
    _queens_update_target_date, _queens_daily_update_target_datetime,
    _parse_queens_update_args, _queens_puzzle_numbers_for_date,
    _queens_puzzle_date_text, _queens_result_message_id, _format_queens_date,
    _is_queens_link_anonymous, _queens_public_link_name,
    _split_queens_anonymous_flag, _is_queens_anonymous_modal_request,
    _clean_queens_linkedin_name, _split_queens_connection_account_text,
    _format_queens_result, _queens_best_results_by_date, _queens_streak_info,
    _QueensAnonymousRegisterModal, _QueensAnonymousRegisterView,
    _QUEENS_SCRAPER_SCRIPT, _QUEENS_DEFAULT_STATE_PATH,
    _AKARI_DIFF_MAX_BYTES, _IMPORT_BATCH_SIZE, _IMPORT_RATE_DELAY,
)
from tle.cogs._minigame_tables import _AKARI_HISTORY_PER_PAGE

logger = logging.getLogger(__name__)


class ImplQueensBackfillMixin:
    async def _read_queens_backfill_entries(self, ctx):
        attachments = list(getattr(ctx.message, 'attachments', None) or [])
        json_atts = [
            a for a in attachments
            if getattr(a, 'filename', '').lower().endswith('.json')]
        if not json_atts:
            raise MinigameCogError(
                'Attach a `queens_history.json` file (generated by '
                '`extra/queens_parse_messages.py`).')
        attachment = json_atts[0]
        size = int(getattr(attachment, 'size', 0) or 0)
        if size and size > _QUEENS_BACKFILL_MAX_BYTES:
            raise MinigameCogError(
                f'Attachment is {size} bytes — refusing anything over '
                f'{_QUEENS_BACKFILL_MAX_BYTES} bytes.')
        raw = await attachment.read()
        try:
            data = json.loads(raw.decode('utf-8'))
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise MinigameCogError(f'Attachment is not valid JSON: {exc}.')
        if not isinstance(data, list):
            raise MinigameCogError(
                'JSON must be a list of result entries.')
        return data

    @staticmethod
    def _parse_queens_backfill_entry(entry):
        if not isinstance(entry, dict):
            raise ValueError('entry is not an object')
        linkedin_name = entry.get('linkedin_name', '')
        if not isinstance(linkedin_name, str) or not linkedin_name.strip():
            raise ValueError('entry has no LinkedIn name')
        linkedin_name = linkedin_name.strip()
        puzzle_number = int(entry['puzzle_number'])
        time_seconds = int(entry['time_seconds'])
        no_hints = bool(entry.get('no_hints', False))
        no_mistakes = bool(entry.get('no_mistakes', False))
        puzzle_date_iso = entry.get('puzzle_date')
        if puzzle_date_iso:
            puzzle_date = dt.date.fromisoformat(puzzle_date_iso)
            expected_date = _queens_date_for_puzzle_number(puzzle_number)
            if puzzle_date != expected_date:
                raise ValueError(
                    f'Queens puzzle #{puzzle_number} is for '
                    f'{expected_date.isoformat()}, not {puzzle_date.isoformat()}')
        else:
            puzzle_date = _queens_date_for_puzzle_number(puzzle_number)
        return (
            normalize_queens_name(linkedin_name),
            _QueensResolvedEntry(
                user_id=None,
                linkedin_name=linkedin_name,
                time_seconds=time_seconds,
                no_hints=no_hints,
                no_mistakes=no_mistakes,
            ),
            puzzle_date,
        )

    @staticmethod
    def _queens_backfill_raw_content(entry):
        return (
            'backfill from LinkedIn export '
            f'({entry.get("sent_at_utc", "")})'
        )

    def _existing_queens_source_rows(self, guild_id, normalized_name,
                                     source_rows_by_name):
        source_rows = source_rows_by_name.get(normalized_name)
        if source_rows is None:
            source_rows = list(
                cf_common.user_db.get_minigame_unresolved_results_for_name(
                    guild_id, QUEENS_GAME.name, normalized_name))
            source_rows_by_name[normalized_name] = source_rows
        return source_rows

    def _remember_queens_source_row(self, source_rows, normalized_name,
                                    parsed, puzzle_date):
        identity_key = self._queens_source_identity_key(
            normalized_name, puzzle_date)
        source_rows[:] = [
            row for row in source_rows
            if self._queens_source_identity_key(
                row.normalized_name, row.puzzle_date) != identity_key
        ]
        source_rows.append(SimpleNamespace(
            normalized_name=normalized_name,
            puzzle_number=_queens_puzzle_number_for_date(puzzle_date),
            puzzle_date=_queens_puzzle_date_text(puzzle_date),
            accuracy=100 if parsed.no_mistakes else 0,
            time_seconds=parsed.time_seconds,
            is_perfect=int(parsed.no_hints and parsed.no_mistakes),
        ))

    def _save_queens_backfill_source_entry(self, ctx, entry, normalized_name,
                                           parsed, puzzle_date, *,
                                           link=None,
                                           source_rows_by_name=None):
        if source_rows_by_name is None:
            source_rows_by_name = {}
        source_rows = self._existing_queens_source_rows(
            ctx.guild.id, normalized_name, source_rows_by_name)
        identity_key = self._queens_source_identity_key(
            normalized_name, puzzle_date)
        existing_rows = [
            row for row in source_rows
            if self._queens_source_identity_key(
                row.normalized_name, row.puzzle_date) == identity_key
        ]
        if any(self._legacy_queens_entry_matches_row(parsed, row)
               for row in existing_rows):
            return False

        if link is not None:
            parsed = parsed._replace(
                user_id=link.user_id,
                linkedin_name=link.external_name,
            )
        self._save_queens_external_result(
            ctx.guild.id, ctx.channel.id, parsed, puzzle_date,
            self._queens_backfill_raw_content(entry))
        self._remember_queens_source_row(
            source_rows, normalized_name, parsed, puzzle_date)
        return True

    def _save_queens_backfill_for_link(self, ctx, link, data):
        target_normalized = link.normalized_name
        matching = []
        for entry in data:
            if not isinstance(entry, dict):
                continue
            name = entry.get('linkedin_name', '')
            if not isinstance(name, str):
                continue
            if normalize_queens_name(name) == target_normalized:
                matching.append(entry)

        saved = 0
        skipped = 0
        malformed = 0
        source_rows_by_name = {}
        for entry in matching:
            try:
                normalized_name, parsed, puzzle_date = (
                    self._parse_queens_backfill_entry(entry))
            except (KeyError, TypeError, ValueError):
                malformed += 1
                continue

            if self._save_queens_backfill_source_entry(
                    ctx, entry, normalized_name, parsed, puzzle_date,
                    link=link, source_rows_by_name=source_rows_by_name):
                saved += 1
            else:
                skipped += 1

        return _QueensBackfillResult(
            link=link,
            matched=len(matching),
            saved=saved,
            skipped=skipped,
            malformed=malformed,
        )

    def _save_queens_backfill_all(self, ctx, data):
        links_by_name = {
            link.normalized_name: link
            for link in cf_common.user_db.get_minigame_player_links(
                ctx.guild.id, QUEENS_GAME.name)
            if not cf_common.user_db.is_minigame_banned(
                ctx.guild.id, QUEENS_GAME.name, link.user_id)
        }
        source_rows_by_name = {}
        saved = 0
        skipped = 0
        malformed = 0
        valid = 0
        registered_names = set()
        unresolved_names = set()
        for entry in data:
            try:
                normalized_name, parsed, puzzle_date = (
                    self._parse_queens_backfill_entry(entry))
            except (KeyError, TypeError, ValueError):
                malformed += 1
                continue
            valid += 1
            link = links_by_name.get(normalized_name)
            if link is None:
                unresolved_names.add(normalized_name)
            else:
                registered_names.add(normalized_name)
            if self._save_queens_backfill_source_entry(
                    ctx, entry, normalized_name, parsed, puzzle_date,
                    link=link, source_rows_by_name=source_rows_by_name):
                saved += 1
            else:
                skipped += 1
        return {
            'saved': saved,
            'skipped': skipped,
            'malformed': malformed,
            'valid': valid,
            'registered_names': registered_names,
            'unresolved_names': unresolved_names,
        }

